# -- number of replicas to deploy
replicaCount: 1

image:
  registry: docker.io
  repository: hapiproject/hapi
  # -- defaults to `Chart.appVersion`
  tag: ""
  # -- the flavor or variant of the image to use.
  # appended to the image tag by `-`.
  flavor: "distroless"
  pullPolicy: IfNotPresent

# -- image pull secrets to use when pulling the image
imagePullSecrets: []

# -- override the chart name
nameOverride: ""

# -- override the chart fullname
fullnameOverride: ""

# -- annotations applied to the server deployment
deploymentAnnotations: {}

# -- annotations applied to the server pod
podAnnotations: {}

# -- pod security context
podSecurityContext:
  {}
  # fsGroup: 2000

<<<<<<< HEAD
# ContainerSecurityContext applied to the container
securityContext: # +doc-gen:ignore
=======
securityContext:
>>>>>>> master
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 65532

<<<<<<< HEAD
service:
  # type of service to expose the server
  type: ClusterIP
  # service port
  port: 8080

ingress:
  # whether to create an Ingress to expose the FHIR server web interface
  enabled: false
  # provide any additional annotations which may be required. Evaluated as a template.
=======
# service to expose the server
service:
  type: ClusterIP
  port: 8080

ingress:
  # -- whether to create an Ingress to expose the FHIR server HTTP endpoint
  enabled: false
  # -- provide any additional annotations which may be required. Evaluated as a template.
>>>>>>> master
  annotations:
    {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
<<<<<<< HEAD
    - host: fhir-server.127.0.0.1.xip.io
      pathType: ImplementationSpecific
      paths: ["/"]
  # ingress TLS config
=======
    - host: fhir-server.127.0.0.1.nip.io
      pathType: ImplementationSpecific
      paths: ["/"]
  # -- ingress TLS config
>>>>>>> master
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

<<<<<<< HEAD
# resource requests and limits
=======
# -- configure the FHIR server's resource requests and limits
>>>>>>> master
resources:
  {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

<<<<<<< HEAD
# node labels for pods assignment
# see: <https://kubernetes.io/docs/user-guide/node-selection/>
nodeSelector: {}

# tolerations for pods assignment
# see: <https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/>
tolerations: []

# affinity for pods assignment
# see: <https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity>
affinity: {}

# see <https://github.com/bitnami/charts/tree/master/bitnami/postgresql> for details
postgresql:
  # enable an included PostgreSQL DB.
  # if set to `false`, the values under `webApi.db` are used
  enabled: true
  # update the default Postgres version to 13.2
  image: # +doc-gen:break
    tag: 13.2.0
  # name of the database to create
  # see: <https://github.com/bitnami/bitnami-docker-postgresql/blob/master/README.md#creating-a-database-on-first-run>
  postgresqlDatabase: "fhir"
  # Name of existing secret to use for PostgreSQL passwords.
=======
# -- node selector for the pod
nodeSelector: {}

# -- pod tolerations
tolerations: []

# -- pod affinity
affinity: {}

postgresql:
  # -- enable an included PostgreSQL DB.
  # see <https://github.com/bitnami/charts/tree/master/bitnami/postgresql> for details
  # if set to `false`, the values under `externalDatabase` are used
  enabled: true
  # -- name of the database to create
  # see: <https://github.com/bitnami/bitnami-docker-postgresql/blob/master/README.md#creating-a-database-on-first-run>
  postgresqlDatabase: "fhir"
  # -- Name of existing secret to use for PostgreSQL passwords.
>>>>>>> master
  # The secret has to contain the keys `postgresql-password`
  # which is the password for `postgresqlUsername` when it is
  # different of `postgres`, `postgresql-postgres-password` which
  # will override `postgresqlPassword`, `postgresql-replication-password`
  # which will override `replication.password` and `postgresql-ldap-password`
  # which will be sed to authenticate on LDAP. The value is evaluated as a template.
  existingSecret: ""
<<<<<<< HEAD
  replication:
    # should be true for production use
    enabled: false
    # number of read replicas
    readReplicas: 2
    # set synchronous commit mode: on, off, remote_apply, remote_write and local
    synchronousCommit: "on"
    # from the number of `readReplicas` defined above, set the number of those that will have synchronous replication
    numSynchronousReplicas: 1
  metrics:
    # should also be true for production use
    enabled: false
    serviceMonitor:
      # create a Prometheus Operator ServiceMonitor resource
      enabled: false
      # the labels used for Prometheus autodiscover, e.g. could be `release: prometheus`
      additionalLabels: {}
  containerSecurityContext: # +doc-gen:ignore
=======
  containerSecurityContext:
>>>>>>> master
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL

<<<<<<< HEAD
# readiness probe
readinessProbe: # +doc-gen:ignore
=======
readinessProbe:
>>>>>>> master
  failureThreshold: 5
  initialDelaySeconds: 30
  periodSeconds: 20
  successThreshold: 1
  timeoutSeconds: 20
<<<<<<< HEAD
# startup probe
startupProbe: # +doc-gen:ignore
=======

startupProbe:
>>>>>>> master
  failureThreshold: 10
  initialDelaySeconds: 60
  periodSeconds: 30
  successThreshold: 1
  timeoutSeconds: 30

<<<<<<< HEAD
# only used if `postgresql.enabeld=false`
externalDatabase:
  # Database host
  host: localhost
  # non-root Username for FHIR Database
  user: fhir
  # Database password
  password: ""
  # Name of an existing secret resource containing the DB password in a 'postgresql-password' key
  existingSecret: ""
  # Database name
  database: fhir
  # Database port number
  port: 5432
=======
externalDatabase:
  # -- external database host used with `postgresql.enabled=false`
  host: localhost
  # -- database port number
  port: 5432
  # -- username for the external database
  user: fhir
  # -- database password
  password: ""
  # -- name of an existing secret resource containing the DB password in the `existingSecretKey` key
  existingSecret: ""
  # -- name of the key inside the `existingSecret`
  existingSecretKey: "postgresql-password"
  # -- database name
  database: fhir

networkPolicy:
  # -- enable NetworkPolicy
  enabled: false
  # -- a Kubernetes LabelSelector to explicitly select namespaces from which ingress traffic could be allowed
  explicitNamespacesSelector:
    {}
    # matchLabels:
    #   team: one
    #   test: foo

  # -- Additional allowed NetworkPolicyPeer specs
  # Evaluated as a template so you could do:
  #
  # Example:
  # allowedFrom:
  #   - podSelector:
  #       matchLabels:
  #         app.kubernetes.io/name: {{ $.Release.Name }}
  allowedFrom: []
>>>>>>> master
