hapi:
  fhir:
    implementationguides:
      cda:
        url: https://github.com/ahdis/cda-core-2.0/releases/download/v0.0.3-dev/package.tgz
        name: hl7.fhir.cda
        version: 2.1.0
      cdach:
        url: http://build.fhir.org/ig/hl7ch/cda-fhir-maps/package.tgz
        name: ch.fhir.ig.cda-fhir-maps
        version: 0.2.0
      iheformatcodefhir:
        url: https://profiles.ihe.net/fhir/ihe.formatcode.fhir/package.tgz
        name: ihe.formatcode.fhir
        version: 1.0.0
#      terminology:
#       name: hl7.terminology.r4
#       version: 2.1.0
      eprterm:
        name: ch.fhir.ig.ch-epr-term
        version: 2.0.6
      core:
        name: ch.fhir.ig.ch-core
        version: 2.0.0
      emed:
        name: ch.fhir.ig.ch-emed
        version: 1.0.0
      vacd:
        name: ch.fhir.ig.ch-vacd
        version: 1.0.0
      atc:
        name: ch.fhir.ig.ch-atc
        version: 3.1.0
      sdc:
        name: hl7.fhir.uv.sdc
        version: 2.7.0
      chorf:
        name: ch.fhir.ig.ch-orf
        version: 0.10.0
      chradorder:
        name: ch.fhir.ig.ch-rad-order
        version: 0.1.0
      chetoc:
        name: ch.fhir.ig.ch-etoc
        version: 0.1.0
      mhd:
        name: ihe.mhd.fhir
        version: 4.0.1      
      pixm:
        name: IHE.ITI.PIXm
        version: 3.0.0
      cheprmhealth:
        url: https://fhir.ch/ig/ch-epr-mhealth/package.tgz
        name: ch.fhir.ig.ch-epr-mhealth
        version: 1.0.0
      challergyintolerance:
        name: ch.fhir.ig.ch-allergyintolerance
        version": 0.2.0
      chradorderpoc:
        url: https://build.fhir.org/ig/ahdis/ch-rad-poc/package.tgz
        name: ch.ahdis.ig.ch-rad-poc
        version: 0.1.0
      chalis:
        url: https://build.fhir.org/ig/ahdis/ch-alis/package.tgz
        name: ch.fhir.ig.ch-alis
        version": 0.2.0